[package]
name = "vision-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
tonic = { version = "0.12", features = ["transport"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.12"
